__title__ = 'keecrypt'
__description__ = 'A keepass alternative written in python'
__url__ = 'http://pdragt.com'
__version__ = '0.0.1'
__author__ = 'Pepijn Dragt'
__author_email__ = 'pepijn.dragt@gmail.com'
__license__ = 'GPL 3.0'
__copyright__ = 'Copyright 2017 Pepijn Dragt'
