__title__ = 'keecrypt'
__description__ = 'keecrypt: A keepass alternative written in python'
__url__ = 'https://github.com/pepijnd/keecrypt'
__version__ = '0.0.1'
__author__ = 'Pepijn Dragt'
__author_email__ = 'pepijn.dragt@gmail.com'
__license__ = 'GPL V3'
__copyright__ = 'Copyright 2017 Pepijn Dragt'
